apiVersion: v1
kind: Service
metadata:
  name: aqueduct-headless
  namespace: aqueduct
  labels:
    app: aqueduct
spec:
  clusterIP: None
  selector:
    app: aqueduct
  ports:
    - name: quic
      port: 4242
      targetPort: 4242
      protocol: UDP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: aqueduct-client
  namespace: aqueduct
  labels:
    app: aqueduct
spec:
  type: ClusterIP
  selector:
    app: aqueduct
  ports:
    - name: quic
      port: 4242
      targetPort: 4242
      protocol: UDP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
