// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/admin/proto/admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetClientQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Rate          int64                  `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClientQuotaRequest) Reset() {
	*x = SetClientQuotaRequest{}
	mi := &file_internal_admin_proto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClientQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClientQuotaRequest) ProtoMessage() {}

func (x *SetClientQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_admin_proto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClientQuotaRequest.ProtoReflect.Descriptor instead.
func (*SetClientQuotaRequest) Descriptor() ([]byte, []int) {
	return file_internal_admin_proto_admin_proto_rawDescGZIP(), []int{0}
}

func (x *SetClientQuotaRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SetClientQuotaRequest) GetRate() int64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type SetClientQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClientQuotaResponse) Reset() {
	*x = SetClientQuotaResponse{}
	mi := &file_internal_admin_proto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClientQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClientQuotaResponse) ProtoMessage() {}

func (x *SetClientQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_admin_proto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClientQuotaResponse.ProtoReflect.Descriptor instead.
func (*SetClientQuotaResponse) Descriptor() ([]byte, []int) {
	return file_internal_admin_proto_admin_proto_rawDescGZIP(), []int{1}
}

func (x *SetClientQuotaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ACLRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Permission    string                 `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACLRule) Reset() {
	*x = ACLRule{}
	mi := &file_internal_admin_proto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACLRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACLRule) ProtoMessage() {}

func (x *ACLRule) ProtoReflect() protoreflect.Message {
	mi := &file_internal_admin_proto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACLRule.ProtoReflect.Descriptor instead.
func (*ACLRule) Descriptor() ([]byte, []int) {
	return file_internal_admin_proto_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ACLRule) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ACLRule) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ACLRule) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

type UpdateACLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*ACLRule             `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateACLRequest) Reset() {
	*x = UpdateACLRequest{}
	mi := &file_internal_admin_proto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateACLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateACLRequest) ProtoMessage() {}

func (x *UpdateACLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_admin_proto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateACLRequest.ProtoReflect.Descriptor instead.
func (*UpdateACLRequest) Descriptor() ([]byte, []int) {
	return file_internal_admin_proto_admin_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateACLRequest) GetRules() []*ACLRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type UpdateACLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RulesCount    int32                  `protobuf:"varint,2,opt,name=rules_count,json=rulesCount,proto3" json:"rules_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateACLResponse) Reset() {
	*x = UpdateACLResponse{}
	mi := &file_internal_admin_proto_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateACLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateACLResponse) ProtoMessage() {}

func (x *UpdateACLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_admin_proto_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateACLResponse.ProtoReflect.Descriptor instead.
func (*UpdateACLResponse) Descriptor() ([]byte, []int) {
	return file_internal_admin_proto_admin_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateACLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateACLResponse) GetRulesCount() int32 {
	if x != nil {
		return x.RulesCount
	}
	return 0
}

var File_internal_admin_proto_admin_proto protoreflect.FileDescriptor

const file_internal_admin_proto_admin_proto_rawDesc = "" +
	"\n" +
	" internal/admin/proto/admin.proto\x12\x05admin\"H\n" +
	"\x15SetClientQuotaRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x03R\x04rate\"2\n" +
	"\x16SetClientQuotaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\\\n" +
	"\aACLRule\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\"8\n" +
	"\x10UpdateACLRequest\x12$\n" +
	"\x05rules\x18\x01 \x03(\v2\x0e.admin.ACLRuleR\x05rules\"N\n" +
	"\x11UpdateACLResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vrules_count\x18\x02 \x01(\x05R\n" +
	"rulesCount2\x9d\x01\n" +
	"\fAdminService\x12M\n" +
	"\x0eSetClientQuota\x12\x1c.admin.SetClientQuotaRequest\x1a\x1d.admin.SetClientQuotaResponse\x12>\n" +
	"\tUpdateACL\x12\x17.admin.UpdateACLRequest\x1a\x18.admin.UpdateACLResponseB?Z=github.com/kshishtovsky/aqueduct/internal/admin/proto;adminpbb\x06proto3"

var (
	file_internal_admin_proto_admin_proto_rawDescOnce sync.Once
	file_internal_admin_proto_admin_proto_rawDescData []byte
)

func file_internal_admin_proto_admin_proto_rawDescGZIP() []byte {
	file_internal_admin_proto_admin_proto_rawDescOnce.Do(func() {
		file_internal_admin_proto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_admin_proto_admin_proto_rawDesc), len(file_internal_admin_proto_admin_proto_rawDesc))) // #nosec G103
	})
	return file_internal_admin_proto_admin_proto_rawDescData
}

var file_internal_admin_proto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_admin_proto_admin_proto_goTypes = []any{
	(*SetClientQuotaRequest)(nil),  // 0: admin.SetClientQuotaRequest
	(*SetClientQuotaResponse)(nil), // 1: admin.SetClientQuotaResponse
	(*ACLRule)(nil),                // 2: admin.ACLRule
	(*UpdateACLRequest)(nil),       // 3: admin.UpdateACLRequest
	(*UpdateACLResponse)(nil),      // 4: admin.UpdateACLResponse
}
var file_internal_admin_proto_admin_proto_depIdxs = []int32{
	2, // 0: admin.UpdateACLRequest.rules:type_name -> admin.ACLRule
	0, // 1: admin.AdminService.SetClientQuota:input_type -> admin.SetClientQuotaRequest
	3, // 2: admin.AdminService.UpdateACL:input_type -> admin.UpdateACLRequest
	1, // 3: admin.AdminService.SetClientQuota:output_type -> admin.SetClientQuotaResponse
	4, // 4: admin.AdminService.UpdateACL:output_type -> admin.UpdateACLResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_admin_proto_admin_proto_init() }
func file_internal_admin_proto_admin_proto_init() {
	if File_internal_admin_proto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			// #nosec G103 -- generated code; protoc-gen-go uses unsafe to view []byte as string.
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_admin_proto_admin_proto_rawDesc), len(file_internal_admin_proto_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_admin_proto_admin_proto_goTypes,
		DependencyIndexes: file_internal_admin_proto_admin_proto_depIdxs,
		MessageInfos:      file_internal_admin_proto_admin_proto_msgTypes,
	}.Build()
	File_internal_admin_proto_admin_proto = out.File
	file_internal_admin_proto_admin_proto_goTypes = nil
	file_internal_admin_proto_admin_proto_depIdxs = nil
}
